import type { StylePreset, TokenValue } from './types';
const base: Record<string, TokenValue> = {
  'font.family': 'Pretendard',
  'font.title': 40,
  'font.body': 16,
  'font.lineHeight': 1.55,
  'font.tracking': 0,
  'radius.card': 16,
  'space.base': 24,
  'effect.blur': 0,
  'effect.glow': 0,
  'effect.decor': 1,
  'motion.duration': 500,
  'color.success': '#51c9a5',
  'color.danger': '#ff758c',
  'color.onAccent': '#10131a',
};
function preset(
  id: string,
  name: string,
  english: string,
  description: string,
  tags: string[],
  accent: string,
  dark: string[],
  light: string[],
  extra: Record<string, TokenValue> = {},
): StylePreset {
  return {
    id,
    name,
    english,
    description,
    tags,
    accent,
    dark: {
      ...base,
      'color.bg': dark[0],
      'color.surface': dark[1],
      'color.text': dark[2],
      'color.muted': dark[3],
      'color.border': dark[4],
      'color.accent': accent,
      ...extra,
    },
    light: {
      ...base,
      'color.bg': light[0],
      'color.surface': light[1],
      'color.text': light[2],
      'color.muted': light[3],
      'color.border': light[4],
      'color.accent': accent,
      ...extra,
    },
  };
}
export const STYLES: StylePreset[] = [
  preset(
    'glass',
    '다크 글라스',
    'MIDNIGHT GLASS',
    '빛과 깊이를 담은 투명한 작업 공간',
    ['글라스', '다크', '제품'],
    '#adbcff',
    ['#0e1220', '#1a2033', '#f1f4ff', '#a9b1cb', '#35405b'],
    ['#eff2fc', '#ffffff', '#172244', '#52617d', '#bbc5df'],
    { 'effect.blur': 20, 'effect.glow': 0.45, 'radius.card': 20 },
  ),
  preset(
    'minimal',
    '업무 미니멀',
    'QUIET FORM',
    '정돈된 여백, 또렷한 메시지',
    ['미니멀', '업무', '보고서'],
    '#629dff',
    ['#111720', '#1c2532', '#f1f5fa', '#a9b8cb', '#3d4c62'],
    ['#f4f6f8', '#ffffff', '#192432', '#536174', '#bac5d3'],
    { 'radius.card': 6, 'effect.decor': 0, 'space.base': 24 },
  ),
  preset(
    'editorial',
    '에디토리얼',
    'THE EDITORIAL',
    '활자와 여백이 만드는 자연스러운 리듬',
    ['타이포', '포트폴리오', '여백'],
    '#dfa488',
    ['#1c1918', '#282321', '#f7ece3', '#c3afa1', '#51443d'],
    ['#f6f0e7', '#fffaf3', '#382c25', '#786558', '#cfc0af'],
    { 'radius.card': 2, 'space.base': 32, 'font.title': 48 },
  ),
  preset(
    'tech',
    '테크',
    'SIGNAL / SYSTEM',
    '선명한 신호와 구조적인 디테일',
    ['테크', '네온', '제품'],
    '#a4f875',
    ['#0d1512', '#17251d', '#e9ffed', '#9db5a4', '#345142'],
    ['#eef5ed', '#fcfffa', '#1d3927', '#546e59', '#b7cfb8'],
    { 'radius.card': 8, 'effect.glow': 0.7, 'effect.blur': 6, 'font.tracking': -0.3 },
  ),
  preset(
    'data',
    '데이터 중심',
    'CLEAR METRICS',
    '숫자에서 시작해 인사이트로 이어지는 화면',
    ['데이터', '대시보드', '업무'],
    '#73d9df',
    ['#0d1820', '#162731', '#effbff', '#a0bdca', '#345363'],
    ['#edf5f7', '#ffffff', '#183b46', '#53737d', '#b7d0d8'],
    { 'radius.card': 10, 'space.base': 16, 'font.body': 15 },
  ),
  preset(
    'cinematic',
    '시네마틱',
    'AFTER HOURS',
    '장면과 타이포그래피에 집중하는 무드',
    ['영상', '모션', '브랜드'],
    '#d1a4ff',
    ['#14101c', '#241b30', '#faf0ff', '#baa6cd', '#513b64'],
    ['#f5edf9', '#fffaff', '#342041', '#755b88', '#d0bcdf'],
    {
      'radius.card': 12,
      'font.title': 52,
      'effect.glow': 0.5,
      'effect.blur': 12,
      'motion.duration': 900,
    },
  ),
];
export const TOKEN_META: Record<
  string,
  {
    label: string;
    group: string;
    description: string;
    type: 'color' | 'number' | 'font';
    min?: number;
    max?: number;
    step?: number;
    unit?: string;
  }
> = {
  'color.accent': {
    label: '주 강조색',
    group: '역할색',
    description: '버튼, 링크, 핵심 데이터',
    type: 'color',
  },
  'color.onAccent': {
    label: '강조색 위 글자',
    group: '역할색',
    description: '강조 버튼의 텍스트',
    type: 'color',
  },
  'color.success': {
    label: '완료·성공',
    group: '역할색',
    description: '정상 상태와 완료 표시',
    type: 'color',
  },
  'color.danger': {
    label: '오류·위험',
    group: '역할색',
    description: '실패와 삭제 행동',
    type: 'color',
  },
  'color.bg': {
    label: '페이지 배경',
    group: '표면과 잉크',
    description: '가장 아래의 바탕',
    type: 'color',
  },
  'color.surface': {
    label: '카드 표면',
    group: '표면과 잉크',
    description: '패널과 카드의 바탕',
    type: 'color',
  },
  'color.text': {
    label: '본문 글자',
    group: '표면과 잉크',
    description: '제목과 기본 텍스트',
    type: 'color',
  },
  'color.muted': {
    label: '보조 글자',
    group: '표면과 잉크',
    description: '캡션과 설명',
    type: 'color',
  },
  'color.border': {
    label: '구분선',
    group: '표면과 잉크',
    description: '장식용 경계선',
    type: 'color',
  },
  'font.family': {
    label: '기본 글꼴',
    group: '타이포그래피',
    description: '한글·영문 본문 글꼴',
    type: 'font',
  },
  'font.title': {
    label: '제목 크기',
    group: '타이포그래피',
    description: '기본 제목 스케일',
    type: 'number',
    min: 12,
    max: 240,
    unit: 'px',
  },
  'font.body': {
    label: '본문 크기',
    group: '타이포그래피',
    description: '읽기 편한 본문 크기',
    type: 'number',
    min: 8,
    max: 120,
    unit: 'px',
  },
  'font.lineHeight': {
    label: '행간',
    group: '타이포그래피',
    description: '글자 크기 대비 줄 높이',
    type: 'number',
    min: 1,
    max: 2.5,
    step: 0.05,
    unit: '×',
  },
  'font.tracking': {
    label: '자간',
    group: '타이포그래피',
    description: '글자 사이 간격',
    type: 'number',
    min: -2,
    max: 8,
    step: 0.1,
    unit: 'px',
  },
  'space.base': {
    label: '기본 여백',
    group: '간격과 모양',
    description: '콘텐츠와 컨테이너 간격',
    type: 'number',
    min: 8,
    max: 64,
    step: 4,
    unit: 'px',
  },
  'radius.card': {
    label: '카드 모서리',
    group: '간격과 모양',
    description: '표면의 둥근 정도',
    type: 'number',
    min: 0,
    max: 40,
    unit: 'px',
  },
  'effect.blur': {
    label: '유리 블러',
    group: '효과와 모션',
    description: '반투명 표면의 배경 흐림',
    type: 'number',
    min: 0,
    max: 40,
    unit: 'px',
  },
  'effect.glow': {
    label: '광원 강도',
    group: '효과와 모션',
    description: '브랜드색 배경 빛',
    type: 'number',
    min: 0,
    max: 1.4,
    step: 0.05,
  },
  'effect.decor': {
    label: '장식 수위',
    group: '효과와 모션',
    description: '전체 장식 효과의 세기',
    type: 'number',
    min: 0,
    max: 1.4,
    step: 0.05,
  },
  'motion.duration': {
    label: '기본 모션 길이',
    group: '효과와 모션',
    description: '장면과 요소 전환 시간',
    type: 'number',
    min: 0,
    max: 3000,
    step: 50,
    unit: 'ms',
  },
};
